
clusterName: ${ cluster_name }

serviceAccount:
  name: ${ service_account_name }

region: ${ region }
vpcId: ${ vpc_id }

tolerations: 
  - key: "system-workload"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  
nodeSelector:
  role: system
