apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: "${ name }"
  namespace: "${ service.namespace }"
  labels: ${ jsonencode(labels) }
spec:
  serviceRef:
    name: "${ service.name }"
    port: ${ service.port }
  targetGroupARN: "${ targetGroupARN }"