
clusterName: ${ cluster_name }

serviceAccount:
  name: ${ service_account_name }

region: ${ region }
vpcId: ${ vpc_id }

tolerations: ${ jsonencode(tolerations) }
  
nodeSelector: ${ jsonencode(node_selector) }
